services:
  # MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: digital-banking-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: digital_banking_db
      MYSQL_USER: banking_user
      MYSQL_PASSWORD: banking_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - banking-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


  # phpMyAdmin for Database Management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: digital-banking-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: my-secret-pw
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - "8081:80"    
    depends_on:
      - mysql-db
    networks:
      - banking-network

volumes:
  mysql_data:
    driver: local

networks:
  banking-network:
    driver: bridge
